apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  replicas: 3  # Set the number of replicas for horizontal scaling
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:latest  # Official ClickHouse image
        ports:
        - containerPort: 8123  # HTTP port for ClickHouse
        - containerPort: 9000   # TCP port for ClickHouse
        env:
        - name: CLICKHOUSE_USER
          value: "default"      # Default user
        - name: CLICKHOUSE_PASSWORD
          value: "password"     # Password for the user
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse  # Persist data
      volumes:
      - name: clickhouse-storage
        persistentVolumeClaim:
          claimName: clickhouse-pvc  # Reference to PVC (Persistent Volume Claim)
