apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - protocol: TCP
    port: 8123  # HTTP port for ClickHouse
    targetPort: 8123
  - protocol: TCP
    port: 9000   # TCP port for ClickHouse
    targetPort: 9000
  type: ClusterIP
