apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
  labels:
    app: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      containers:
      - name: data-processing
        image: nginx  # Replace this with your actual data processing image
        ports:
        - containerPort: 80
